### ISSUE TITLE
Design information graphic

### ISSUE THREAD

**Issue by venkatrajam** [info-design-lab/DE134#2]
In this assignment you will design a graphic to show the correlation between the polling phases and results of the WB assembly elections.  Wikipedia [has a page](https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election) that is comprehensive and authentic enough for the purpose of this assignment. You may use other sources, but must acknowledge them in your references. Focus on designing the information, rather the design of the visual. Think about what organisation of the information will lead to achieving your objectives.

**Comment by Ishitasharmax** [comment]
**Output 1**
![WBElections](https://user-images.githubusercontent.com/83575342/117617309-fe4c9600-b189-11eb-9a14-ca6fc4181004.jpg)


**Output 2**
![WBElections2](https://user-images.githubusercontent.com/83575342/117278553-7eb78200-ae7e-11eb-9746-c474a61d0818.jpg)

**Comment by Kushagra-Kishore** [comment]
### West Bengal Election 2021
![2](https://user-images.githubusercontent.com/83573797/117326171-06b58000-aeaf-11eb-8f3f-be44a2ce9a2e.jpg)



Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election

I chose to represent the phase-wise results in the form of a line graph as I think this way it is easier to see the change in the number of seats as we progress through the phases. It is also easier to compare the trajectories of the two parties.

The only problem with this graph is that it is difficult to picture the percentage of seats won by each party in each phase, even though the total no. of seats available per phase is provided. A bar graph would have been better suited to see the percentages of seats won in each phase, but then it would become difficult to compare the trajectories of each party. I feel it is more important to be able to see clearly how each party performed in itself as well as with respect to the other, which is why I went with this graph.

**Comment by NiveaChoudhary** [comment]
![west bengal-01](https://user-images.githubusercontent.com/83574263/117189627-0a3bff00-adfc-11eb-833a-643d9ed62f73.png)

I used percentage in my infograph because in my opinion common people doesn't want to know the exact number of seats they just want to get a rough idea of who is winning. In my graph length is coded to show percentage of seats and color is coded to give information about the party.

Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election

**Comment by ryanhmar** [comment]
![Graph](https://user-images.githubusercontent.com/83573560/117191232-f396a780-adfd-11eb-9abb-330c4e086464.png)

Reference: [https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election](url)

I have made a graph that represents the elections in the 8 phases with the percentage of seats taken by each party instead of showing the total seat count in each phase. My reasoning behind this is that it displays the important information of the election, i.e. who is winning, immediately without having to analyze the graph for more than a minute.

**Comment by AbhimanyuUllas** [comment]
**Total no of seats won by each parties.**

![Artboard 1](https://user-images.githubusercontent.com/83575497/117313664-ba187780-aea3-11eb-8acc-e383e2eaf282.png)


**No of seats won X Phases of Election** GRAPH

![4](https://user-images.githubusercontent.com/83575497/117313717-c56ba300-aea3-11eb-847b-b9d3cdbd784a.png)


I have created two graphs,

1. Representation of total seats won by each of the parties. I have managed to create a replica of the West Bengal map to represent the areas where the parties have secured seats.
2. Graph representing the seats won by each parties in each phase of the election.

Reference : https://www.news18.com/assembly-elections-2021/west-bengal/alliance-wise-tally-results/
                   https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election

**Comment by minhasmohammed** [comment]
first draft
![0001](https://user-images.githubusercontent.com/83582788/117617224-de1cd700-b189-11eb-8439-4a27a9a56e45.jpg)
second draft
![wb](https://user-images.githubusercontent.com/83582788/117574750-2beafe00-b0fc-11eb-94f8-15f146e23eb9.jpg)


Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election

**Comment by KrishShah2** [comment]
![Slide1](https://user-images.githubusercontent.com/83575362/117198016-1dec6300-ae06-11eb-9086-4789c9d1ba6a.PNG)

Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election

**Comment by AmishaNair** [comment]
Version 1
![Artboard 3@300x](https://user-images.githubusercontent.com/83575248/117773511-04a84400-b256-11eb-986e-91883768408a.png)

Version 2
![Artboard 4@300x](https://user-images.githubusercontent.com/83575248/117773544-0f62d900-b256-11eb-8c22-e71e014427f6.png)

Version 3
![Final Infographic@300x-100](https://user-images.githubusercontent.com/83575248/117775625-4f2ac000-b258-11eb-80ee-1eabf71a4095.jpg)

Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election
My objectives were to show the facts - how many seats each party managed to obtain, and how that varied over time.

**Comment by Ishaan-idc** [comment]
![DE-134infographic3](https://user-images.githubusercontent.com/83575414/117244996-b101b900-ae57-11eb-9cac-356301fb520c.jpg)

My infographic shows the cumulative percentage by the phases completed. This way we get an idea what percentage of seats is won by any party from the seats that have been voted from.

**Comment by Pratham-IDC** [comment]
![BENGAL-ELEC-INFO](https://user-images.githubusercontent.com/83578338/117201241-0fa04600-ae0a-11eb-9004-281145e7a3ea.jpg)
This infographic shows the poll events as well as poll results simultaneously and total no. of seats won by the parties.

**Comment by romapandya49** [comment]
Version 1

![WhatsApp Image 2021-05-10 at 12 22 33](https://user-images.githubusercontent.com/83573626/117618000-f8a38000-b18a-11eb-805e-6905e34d7349.jpeg)

Version 2
![IMG-20210506-WA0084](https://user-images.githubusercontent.com/83573626/117254147-acdc9800-ae65-11eb-9ae6-8561014f782f.jpg)



I represented the correlation of Phases and Results by showing the map of the 8 phases and a bar graph showing how each party fared in each phase. 
References: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Electoral_system

**Comment by Anusree-NS** [comment]
![wb 2021 elections](https://user-images.githubusercontent.com/83588606/117253139-81a57900-ae64-11eb-86a3-d6ebd0f7873c.png)

**Comment by dxgxntx** [comment]
![Screenshot (82)](https://user-images.githubusercontent.com/83574103/117208064-52661c00-ae12-11eb-8a3b-428b0ff9fd91.png)
![Screenshot (78)](https://user-images.githubusercontent.com/83574103/117208073-542fdf80-ae12-11eb-9408-d061637003cd.png)
![Screenshot (86)](https://user-images.githubusercontent.com/83574103/117250969-a2200400-ae61-11eb-879f-860f33c029c4.png)
![Screenshot (89)](https://user-images.githubusercontent.com/83574103/117562674-5cac4280-b0be-11eb-806b-0d46b8665b0e.png)
![Screenshot (81)](https://user-images.githubusercontent.com/83574103/117208089-585bfd00-ae12-11eb-9c54-b02e18f4c071.png)

**Comment by A-b-h-i-s-h-e-k-D-u-t-t-a** [comment]
![WB map](https://user-images.githubusercontent.com/83583741/117349065-9a477a80-aec8-11eb-9626-aec1e01a1c64.jpg)

**Comment by Juii28** [comment]
West Bengal elections 2021 I tried to show the number of seats secured by parties in different phases.
![WEST BENGAL ELECTION 2021 (2)](https://user-images.githubusercontent.com/83611708/118025048-06b8f280-b37d-11eb-8566-d54f4a84ca22.png)

![image](https://user-images.githubusercontent.com/83611708/117438060-ae35bf80-af4e-11eb-8e55-07efc89e3136.jpeg)

**Comment by 20U130005** [comment]
Version 1:
![Elections Infographics 1-01](https://user-images.githubusercontent.com/83573878/118351133-bce82c00-b577-11eb-92fb-1db32f9e3c6c.jpg)

Version 2:
![Elections Infographics2-01](https://user-images.githubusercontent.com/83573878/118351579-7b0cb500-b57a-11eb-9d43-d81dbcf73d3c.jpg)

**Comment by AadishGeorge36** [comment]
![Aadishcdd](https://user-images.githubusercontent.com/83620933/117776173-e1cb5f00-b258-11eb-849f-50ad0501b27b.jpg)

**Comment by AbhiramNS6** [comment]
![Screenshot (195)](https://user-images.githubusercontent.com/83595023/117241430-c7f0dd00-ae50-11eb-9bdc-14b983e1d44b.png)

DRAFT 2
![Screenshot (246)](https://user-images.githubusercontent.com/83595023/118371268-758a8b80-b5c9-11eb-90cb-53e21ab2017e.png)

**Comment by swapnildeycr** [comment]
![Final Version](https://user-images.githubusercontent.com/83583900/117243788-80b91b00-ae55-11eb-9266-befc98d562fe.jpg)



The following infograph is an experimental version that I was trying out, which intended to showcase the ratio of TCM:BJP in terms of seat side by side with the geographical locations of the phases. It turned out to be very messy so the idea was scratched out.

![Experimental](https://user-images.githubusercontent.com/83583900/117243955-c8d83d80-ae55-11eb-98e6-a8d7fad2bc57.jpg)

**Comment by aryamansingh20** [comment]
![Infographic](https://user-images.githubusercontent.com/83575358/117244060-0046ea00-ae56-11eb-8140-aba5720375d0.jpg)

**Comment by deep-savalia** [comment]
![West Bengal 2021](https://user-images.githubusercontent.com/83625972/117244622-012c4b80-ae57-11eb-847e-f4d3dd7dcc70.png)

**Comment by tanushkasarang** [comment]
**Draft 1**
![image](https://user-images.githubusercontent.com/83626981/117245564-b1e71a80-ae58-11eb-8759-f5aff18e4654.png)
**Draft 2**

![image](https://user-images.githubusercontent.com/83626981/118399312-35371600-b67a-11eb-8c28-7da8658bf23e.png)

I have changed the layout and the representation technique, I have used a pyramid graph to show the rise and fall of the respective parties in reference to the phases.

**Comment by mdawkhar** [comment]
**Draft 1**

![Election draft1](https://user-images.githubusercontent.com/83584046/117447459-2dc98b80-af5b-11eb-98f1-f62ead850049.jpg)

**Draft 2** 
Changed the color of map to a single Hue to show Ordinal scale. Increased the thickness of stroke of the Seats won map.

![Election_3](https://user-images.githubusercontent.com/83584046/117527747-e5a67980-afeb-11eb-9589-24fe2983ce32.jpg)

**Draft 3**
I changed the arrangement of the content to help the reader to see both maps closely. And changed stroke color of the phases map (blue one) to light blue for distinguishing boundaries.

![Election_4](https://user-images.githubusercontent.com/83584046/117443643-120fb680-af56-11eb-94ca-871db68a8377.jpg)

**Draft 4**
I changed the blue saturation levels for the map.

![Election_final 3](https://user-images.githubusercontent.com/83584046/117470591-983af580-af74-11eb-863b-50005f4c220c.jpg)

**Comment by HarshSPatil** [comment]
![image](https://user-images.githubusercontent.com/83597822/117248519-bd891000-ae5d-11eb-8424-e331bd7a411b.png)

**Comment by aryamansingh20** [comment]
![Infographic 2](https://user-images.githubusercontent.com/83575358/117248919-528c0900-ae5e-11eb-8feb-014cad216a11.jpg)

**Comment by AjinkyaRaskar4** [comment]
![11](https://user-images.githubusercontent.com/83605850/117252798-165ba700-ae64-11eb-8287-baa4b61a615c.jpg)

**Comment by aryamansingh20** [comment]
![Infographic 2](https://user-images.githubusercontent.com/83575358/117260853-20ce6e80-ae6d-11eb-8b87-ec839950fb78.jpg)

**Comment by aryamansingh20** [comment]
![Infographic 3](https://user-images.githubusercontent.com/83575358/117261127-6ab75480-ae6d-11eb-909f-bdf91ae25349.jpg)

**Comment by 20U130022** [comment]
![sdghfg](https://user-images.githubusercontent.com/83587414/117315284-2c3d8c00-aea5-11eb-9977-99ba392760fe.jpg)

**Comment by Naman-Verma-gg** [comment]
1)  WITH THE POLITICAL PARTIES AS THE SERIES ENTRIES
![image](https://user-images.githubusercontent.com/83628869/117489652-7ef17380-af8b-11eb-8f74-673235cd4d50.png)


2) WITH THE PHASES AS THE SERIES ENTRIES
![image](https://user-images.githubusercontent.com/83628869/117341557-e8a44b80-aebf-11eb-9628-06738a9f34d5.png)

 Reference : https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Results_by_Polling_Phase

**Comment by swapnildeycr** [comment]
![VersionLast](https://user-images.githubusercontent.com/83583900/117339963-fce74900-aebd-11eb-8b40-42d483740fd1.jpg)

**Comment by PalakKatiyar09** [comment]
![graph elections6](https://user-images.githubusercontent.com/83607888/117481776-143b3a80-af81-11eb-90ba-48277550c7c5.png)

Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Results_by_Polling_Phase

**Comment by NavdeepPKumar** [comment]
![IMG_1588](https://user-images.githubusercontent.com/83628609/117405313-12de2380-af29-11eb-8712-8e09c45f4d3b.jpeg)

Edited -
![D50F99DF-DEC0-45EC-A929-CF5AB5D7AB02](https://user-images.githubusercontent.com/83628609/117530374-800db980-affa-11eb-9d2c-22193012c800.jpeg)
Reference : https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Results_by_Polling_Phase

**Comment by pavanxs** [comment]
![qw](https://user-images.githubusercontent.com/83165442/118563950-15dcdd80-b78d-11eb-8c24-00f5ed0b34f5.png)


I made a graph which shows the percentage of seats won so people can quickly figure out who is winning as phases progress.

![qw (1)](https://user-images.githubusercontent.com/83165442/118564037-3a38ba00-b78d-11eb-8d4d-2edf1a3f9822.png)

Reference: https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Results_by_Polling_Phase

**Comment by aryamansingh20** [comment]
![Infographic 2](https://user-images.githubusercontent.com/83575358/117576824-eb43b280-b104-11eb-85e5-9ddf9b8d73b7.jpg)
Draft 1

![Infographic 3](https://user-images.githubusercontent.com/83575358/117576829-f4348400-b104-11eb-988c-e96d2d971a29.jpg)
Draft 2

![Infographic 4](https://user-images.githubusercontent.com/83575358/117577780-e2ed7680-b108-11eb-8ccd-33cef064ec5c.jpg)
Draft 3

**Comment by Suraj-Sadanandan** [comment]
![West Bengal elections_page-0001](https://user-images.githubusercontent.com/83575714/118277436-6b439100-b4e6-11eb-9c8e-01cd5685bf81.jpg)
![West Bengal elections_page-0002](https://user-images.githubusercontent.com/83575714/118279361-b068c280-b4e8-11eb-9366-002a10a904b5.jpg)

Reference[https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election](url)

**Comment by Numaan-Akhtar18** [comment]
![WB5](https://user-images.githubusercontent.com/83707499/123555335-c4b80480-d7a2-11eb-8af9-d64d05c9375f.png)
![WB3](https://user-images.githubusercontent.com/83707499/123555347-da2d2e80-d7a2-11eb-9f7e-80d4976f24e4.png)

Reference:  https://en.wikipedia.org/wiki/2021_West_Bengal_Legislative_Assembly_election#Results_by_Polling_Phase
