### ISSUE TITLE
2021 Wordless Diagrams

### ISSUE THREAD

**Issue by venkatrajam** [info-design-lab/DE134#3]
Pouring milk from a packet or changing a diaper may seem like mundane activities, but when visually presented on paper in step-by-step diagrams, they take on unusual lives of their own. In this assignment you will create a wordless diagram(s) to instruct how to perform an activity that is made of discreet steps, such putting something together or doing something. The objective of this assignment is to understand how humans produce and use visual instructions.

Specifically the assignment requires:
Planning: Most tasks can be done in a variety of ways. The challenge is to choose a sequence of operations that will be easy for users to understand and follow.
Presentation: There are many ways to depict the operations. The challenge is to convey the steps of the operations clearly in a series of diagrams.

STAGES
1. Select a task or operation you want to depict
2. Sketch at least five alternative visual style, layout & sequence of visuals for the selected task/operation
3. Create a full-size pencil rough showing all information for the selected presentation
4. Compose final sequence to create a poster, full color or mock up of fold if user manual

Add a comment and keep updating the progress of your work within the same comment.

**Comment by aryamansingh20** [comment]
![1](https://user-images.githubusercontent.com/83575358/117576444-a9fed300-b103-11eb-9041-dcadad9ad967.jpg)
1st Idea

![2](https://user-images.githubusercontent.com/83575358/117576458-baaf4900-b103-11eb-891a-006f6cd67266.jpg)
2nd Idea

![3](https://user-images.githubusercontent.com/83575358/117576465-c00c9380-b103-11eb-87fc-d17bb4cbeb48.jpg)
3rd Idea

Final Output -->
![edited together](https://user-images.githubusercontent.com/83575358/117646449-678fd180-b1a9-11eb-9ea1-87ffa1b5770b.jpg)

**Comment by NiveaChoudhary** [comment]
**Changing Guitar string**

1.
![Untitled presentation (3)](https://user-images.githubusercontent.com/83574263/117576915-365dc580-b105-11eb-9d11-66093b1bd2a0.jpg)

2.
![Untitled presentation (4)](https://user-images.githubusercontent.com/83574263/117576916-378ef280-b105-11eb-9d18-897df41980e4.jpg)

3.
![Untitled presentation](https://user-images.githubusercontent.com/83574263/117576917-38278900-b105-11eb-9f77-5d0a7ca02f9b.jpg)

4.
![Untitled presentation (1)](https://user-images.githubusercontent.com/83574263/117576918-38c01f80-b105-11eb-8ec1-224c222da6cd.jpg)

5.
![Untitled presentation (2)](https://user-images.githubusercontent.com/83574263/117576919-38c01f80-b105-11eb-8ece-698b8ff4c627.jpg)

**Final**

![guitar-01](https://user-images.githubusercontent.com/83574263/117766142-be021c00-b24c-11eb-87b0-4d693b6839db.png)

**Comment by Ishitasharmax** [comment]
**Task: Making Fried Egg: Sunny Side Up**

_Initial Ideation_
![WD5](https://user-images.githubusercontent.com/83575342/117577011-a4a28800-b105-11eb-87f3-10d4f7e82641.jpg)

_Layout_
![WD4](https://user-images.githubusercontent.com/83575342/117577033-c13ec000-b105-11eb-8b45-de6224e65407.jpg)

_Idea 1_
![WD3](https://user-images.githubusercontent.com/83575342/117577049-cbf95500-b105-11eb-9419-e049f333d83b.jpg)

_Idea 2_
First frame, ingredients.
Depicting heat differently.
![WD2](https://user-images.githubusercontent.com/83575342/117577087-f814d600-b105-11eb-9d18-6238d3dac4bd.jpg)

_Idea 3_
Final Heat Depiction.
Oil Measurement.
![WD1](https://user-images.githubusercontent.com/83575342/117577123-20043980-b106-11eb-99e1-f566825bf010.jpg)

**Output 1** 
_Horizontal Layout_ 
Ease in Reading.
![wordlessdiagramH-01](https://user-images.githubusercontent.com/83575342/117577133-2e525580-b106-11eb-9962-e04fe33d1403.jpg)

**Output 2**
Vertical Alignment
![wordlessdiagramV-02](https://user-images.githubusercontent.com/83575342/117577163-475b0680-b106-11eb-9adc-83c402f58db2.jpg)

**Final Outputs**
1. Cumulative time added
![wordlessdiagramnormal-02](https://user-images.githubusercontent.com/83575342/117654618-9dd24e80-b1b3-11eb-9b0a-a60f4e1ad7e4.jpg)

2. Background Design 1
![wordlessdiagrambg-03](https://user-images.githubusercontent.com/83575342/117654759-d540fb00-b1b3-11eb-8131-1e7ed6e952a9.jpg)


3. Background Design 2
![wordlessdiagramBackground-03](https://user-images.githubusercontent.com/83575342/117654781-dd993600-b1b3-11eb-91d6-5977737310f3.jpg)

**Comment by HarshSPatil** [comment]
How to start a bike 
rough ideas
![Scan 09-May-2021_1](https://user-images.githubusercontent.com/83597822/117579805-31534300-b112-11eb-8d7c-a14b9f357ff4.jpg)
![1620622831368](https://user-images.githubusercontent.com/83597822/117608193-31d3f400-b17b-11eb-87c7-47d966143f31.jpg)
![wordless information-Recovered](https://user-images.githubusercontent.com/83597822/117808756-e6087400-b27a-11eb-9a9c-ef99ad1a7daa.jpg)

**Comment by Kushagra-Kishore** [comment]
### How to appear more confident 

### Version 1
![IMG_20210509_151122-02](https://user-images.githubusercontent.com/83573797/117580522-edfad380-b115-11eb-87ca-f5ecddee1e95.jpeg)

### Version 2
![IMG_20210509_151103-01](https://user-images.githubusercontent.com/83573797/117580570-24d0e980-b116-11eb-8688-77bde22d7d2a.jpeg)

### Version 3
![IMG_20210509_172551-01](https://user-images.githubusercontent.com/83573797/117580618-682b5800-b116-11eb-88ea-7286792ce007.jpeg)

### Version 4
![1 1](https://user-images.githubusercontent.com/83573797/117580686-bd676980-b116-11eb-87fd-a400900e40fb.jpg)

### Version 5
![1 1 final](https://user-images.githubusercontent.com/83573797/118353246-0ab66180-b583-11eb-9d1e-7a76e4962a5f.jpg)

**Comment by dxgxntx** [comment]
How to insert a SIM in a phone
1.
![IMG_1172](https://user-images.githubusercontent.com/83574103/117580924-cdcc1400-b117-11eb-8612-a2d2f2ca64bf.JPG)
2.
![IMG_1179](https://user-images.githubusercontent.com/83574103/117580931-d290c800-b117-11eb-9819-2f6274f9c142.JPG)
3.
![IMG_1174](https://user-images.githubusercontent.com/83574103/117580934-d6244f00-b117-11eb-8f15-5f848bd4f305.JPG)
4.
![IMG_1184](https://user-images.githubusercontent.com/83574103/117580937-d91f3f80-b117-11eb-9a3b-8087d554b449.JPG)
Final image
![1](https://user-images.githubusercontent.com/83574103/117781471-5359dc00-b25e-11eb-8ee6-78f65c527f4a.png)

**Comment by Pratham-IDC** [comment]
Task :How to put Sim in smartphone. 

Visual styles :
![PicsArt_05-09-10.45.37.jpg](https://user-images.githubusercontent.com/83578338/117581376-08cf4700-b11a-11eb-9985-873055e3dd8f.jpg)

Layouts:
![PicsArt_05-09-10.52.18__01.jpg](https://user-images.githubusercontent.com/83578338/117581382-11278200-b11a-11eb-88bc-1e4d0539e685.jpg)

Output 1. (horizontal) 
![INFO-DRWING](https://user-images.githubusercontent.com/83578338/117773003-6d42f100-b255-11eb-9ab6-b24bd6770e53.jpg)


Output 2. (Vertical) 
![INFO-DRWING-2](https://user-images.githubusercontent.com/83578338/117773027-73d16880-b255-11eb-9b1c-ca8d453644b6.jpg)

**Comment by ryanhmar** [comment]
### **How to remove, charge and re-insert Nikon DSLR Battery**
**Drafts**
![1620582106084](https://user-images.githubusercontent.com/83573560/117581797-4339e380-b11c-11eb-87ea-da85f974089e.jpg)
![1620582106096](https://user-images.githubusercontent.com/83573560/117581799-492fc480-b11c-11eb-839e-f1beaa3a724d.jpg)
![1620582106105](https://user-images.githubusercontent.com/83573560/117581801-4b921e80-b11c-11eb-9169-235d2428e9ba.jpg)
![1620582106115](https://user-images.githubusercontent.com/83573560/117581802-4d5be200-b11c-11eb-9645-581640c14d52.jpg)
![1620582106126](https://user-images.githubusercontent.com/83573560/117581804-4fbe3c00-b11c-11eb-82c9-1aa2956977b7.jpg)
**Final idea**
![Instruction final](https://user-images.githubusercontent.com/83573560/117617102-b0d02900-b189-11eb-9fe0-a0464ccae71d.png)
**Final Final Idea**
![Instruction final 2](https://user-images.githubusercontent.com/83573560/117616416-bbd68980-b188-11eb-95b5-9560526f74bd.png)

**Comment by minhasmohammed** [comment]
To draw a circle with a compass
1
![DSCF6097](https://user-images.githubusercontent.com/83582788/117581885-e25edb00-b11c-11eb-9872-fffdea6f6cb4.JPG)
2
![DSCF6098](https://user-images.githubusercontent.com/83582788/117581905-015d6d00-b11d-11eb-9616-481168af6c99.JPG)
3
![DSCF6099](https://user-images.githubusercontent.com/83582788/117581910-09b5a800-b11d-11eb-9ea0-749d7c9f9114.JPG)


How to refill a fountain pen
![DSCF6101](https://user-images.githubusercontent.com/83582788/117764617-6d89bf00-b24a-11eb-9dd0-33baec970c62.JPG)
incomplete draft
![fpen4](https://user-images.githubusercontent.com/83582788/117771446-be51e580-b253-11eb-92e0-98b0bc1aa33c.jpg)

Final
![fpen5](https://user-images.githubusercontent.com/83582788/117776822-949bbd00-b259-11eb-892c-e2ee896197ad.jpg)

**Comment by Juii28** [comment]
DRAFT 1 
how chess pieces move,  for beginner
![IMG-6480](https://user-images.githubusercontent.com/83611708/117583340-4e910d00-b124-11eb-9f37-63a5f626863e.jpg)

DRAFT 2
![IMG_6486](https://user-images.githubusercontent.com/83611708/117609035-ddca0f00-b17c-11eb-996d-22dbe9443593.jpg)

DRAFT 3
![IMG_6485](https://user-images.githubusercontent.com/83611708/117585152-75544100-b12e-11eb-839a-aaac3dc82fe3.jpg)
 Draft 4
![image](https://user-images.githubusercontent.com/83611708/117773091-8a77bf80-b255-11eb-9243-55bb701ea7e5.jpeg)

Final 
![image](https://user-images.githubusercontent.com/83611708/117827551-b5cad080-b28e-11eb-9788-4044d8feed6b.jpeg)

**Comment by AbhiramNS6** [comment]
1
![IMG_20210510_093728](https://user-images.githubusercontent.com/83595023/117605336-1239cd00-b175-11eb-83d6-8e714d60978b.jpg)
2
![IMG_20210510_093954](https://user-images.githubusercontent.com/83595023/117605358-1c5bcb80-b175-11eb-8bd7-83a7b81ef570.jpg)
3
![IMG_20210510_093838](https://user-images.githubusercontent.com/83595023/117605393-31385f00-b175-11eb-80eb-85ea96a62e16.jpg)

Making Bread Omelette 


![Screenshot (199)](https://user-images.githubusercontent.com/83595023/117769835-d88ac400-b251-11eb-962b-52728781adb3.png)

**Comment by romapandya49** [comment]
![IMG_20210510_021056__01](https://user-images.githubusercontent.com/83573626/117586342-383f7d00-b135-11eb-8253-eb65c62efa39.jpg)

![IMG_20210510_021023__01](https://user-images.githubusercontent.com/83573626/117586347-442b3f00-b135-11eb-9118-20b4bfc4d19b.jpg)
![IMG_20210510_020932__01](https://user-images.githubusercontent.com/83573626/117586357-4d1c1080-b135-11eb-971c-632cbde3f886.jpg)
Three drafts of the procedure of making a grilled cheese sandwich.
![IMG_4255](https://user-images.githubusercontent.com/83573626/117715479-f4f91300-b1f5-11eb-83b9-bace504eeb1f.JPG)
Final version

**Comment by AmishaNair** [comment]
![IMG_20210510_020823](https://user-images.githubusercontent.com/83575248/117586415-a71cd600-b135-11eb-8dd8-68fbc74b4457.jpg)
![IMG_20210510_020743](https://user-images.githubusercontent.com/83575248/117586417-a97f3000-b135-11eb-907f-cb30011dc9a2.jpg)
![instruction](https://user-images.githubusercontent.com/83575248/117586423-b6038880-b135-11eb-8b94-bbffdba1d52b.jpg)
Final Output: 
Hair colour fitted to palette, numbers changed to a more readable sans serif
![French braid 2](https://user-images.githubusercontent.com/83575248/117668784-e4c84000-b1c3-11eb-9f1d-9433e608a956.jpg)

**Comment by AbhimanyuUllas** [comment]
**Inserting staple pin into a stapler**

**IDEATION**

**1**

![IMG_20210510_004021-01.jpeg](https://user-images.githubusercontent.com/83575497/117586561-81440100-b136-11eb-829b-f09feb5e133c.jpeg)

**2**

![IMG_20210510_021724-01.jpeg](https://user-images.githubusercontent.com/83575497/117586566-8c972c80-b136-11eb-899d-182eb14774ad.jpeg)

**FINAL**

![Artboard 1](https://user-images.githubusercontent.com/83575497/117700787-19e48a80-b1e4-11eb-99a9-55592600b09e.png)

**MOCKUP**

![Bi fold brochureaaa](https://user-images.githubusercontent.com/83575497/118094264-22a7ad00-b3ec-11eb-86da-e7dfdbc63784.png)

**Comment by Ishaan-idc** [comment]
How to replace a lens on an SLR
![Camera_manual_design_01](https://user-images.githubusercontent.com/83575414/117587765-12b67180-b13d-11eb-900e-377be23c2614.jpg)
![IMG_20210510_030155~2](https://user-images.githubusercontent.com/83575414/117587769-1944e900-b13d-11eb-83f5-78a3c5e042a5.jpg)
![IMG_20210510_025932](https://user-images.githubusercontent.com/83575414/117587816-5b6e2a80-b13d-11eb-9bb4-b4fef386b1bf.jpg)
![Wordless_Diagram_Lens_Change 3](https://user-images.githubusercontent.com/83575414/118349997-f28a1680-b571-11eb-95a2-c6ef54d674fd.png)
![camera manual mockup](https://user-images.githubusercontent.com/83575414/118169415-8a8ae180-b446-11eb-9993-998a5684381b.jpg)

**Comment by Anusree-NS** [comment]
### **How to wash a plushie**

Ideation
![20210510_030653-01](https://user-images.githubusercontent.com/83588606/117587925-01ba3000-b13e-11eb-9eb3-7dd0a2336dc5.jpeg)

Sketches
1. 
![Untitled163_20210510023458](https://user-images.githubusercontent.com/83588606/117587984-5067ca00-b13e-11eb-8173-b47919cc59fa.png)
2.
![Untitled164_20210510030030](https://user-images.githubusercontent.com/83588606/117587961-34642880-b13e-11eb-8a84-df7f8bf13e5e.png)
3.
![Untitled165_20210510031435](https://user-images.githubusercontent.com/83588606/117587962-35955580-b13e-11eb-805b-51817acd2cb6.png)

Final
![washplush](https://user-images.githubusercontent.com/83588606/117829996-df84f700-b290-11eb-9864-97dbbf6e000e.png)

**Comment by 20U130005** [comment]
Taut-line hitch

How to make an adjustable loop knot for use on lines under tension.


Style 1: 
![New doc 10 May 2021 7 40 am-1](https://user-images.githubusercontent.com/83573878/117597944-42c53b00-b164-11eb-9084-a87d68fb32e8.jpg)

Style 2:
![New doc 10 May 2021 7 42 am-1](https://user-images.githubusercontent.com/83573878/117597951-4658c200-b164-11eb-8042-5f29054aa132.jpg)

Style 3: In the angle of the user
![New doc 10 May 2021 9 33 am-1](https://user-images.githubusercontent.com/83573878/117604551-55933c00-b173-11eb-8887-72c4745b4707.jpg)

Other ways to show:
![New doc 10 May 2021 9 35 am-1](https://user-images.githubusercontent.com/83573878/117604561-59bf5980-b173-11eb-8d09-e563cd9b6b86.jpg)
![New doc 10 May 2021 10 28 am-1](https://user-images.githubusercontent.com/83573878/117607931-a5c1cc80-b17a-11eb-8474-46f5af4b1a9f.jpg)
![New doc 10 May 2021 11 18 am-1(1)](https://user-images.githubusercontent.com/83573878/117612083-3fd94300-b182-11eb-8a9e-3f0ffdbb996b.jpg)


All steps one diagram:
![New doc 10 May 2021 11 21 am-1](https://user-images.githubusercontent.com/83573878/117612126-5089b900-b182-11eb-8fdc-6e641d6f0598.jpg)



I can also show the possible uses using diagrams:

 backpack sack,  hanging clothes, boating/sailing, outdoor, home and garden
![New doc 10 May 2021 11 37 am-1](https://user-images.githubusercontent.com/83573878/117613237-3224bd00-b184-11eb-84e9-65b46f4462ee.jpg)


![TAUT HITCH-01](https://user-images.githubusercontent.com/83573878/118312554-2c760100-b50f-11eb-930d-912607188bb3.jpg)
![TAUT HITCH-02](https://user-images.githubusercontent.com/83573878/118312560-2e3fc480-b50f-11eb-8b87-80729fdfbbbd.jpg)
![TAUT HITCH-03](https://user-images.githubusercontent.com/83573878/118312563-2f70f180-b50f-11eb-8093-e9b10de1c64e.jpg)

![Step by step-03](https://user-images.githubusercontent.com/83573878/118348060-4f330480-b565-11eb-937a-64a0a49cbb84.jpg)

![Step by step-05](https://user-images.githubusercontent.com/83573878/118349019-b3f15d80-b56b-11eb-8139-84c90e309e23.jpg)

![Step by step5-05](https://user-images.githubusercontent.com/83573878/118350062-5280bd00-b572-11eb-8ac1-bfc939b6df25.jpg)

**Comment by AadishGeorge36** [comment]
Topic - How to Frame a Photograph
![1](https://user-images.githubusercontent.com/83620933/117602141-98eaac00-b16d-11eb-9c74-bf14322a286d.jpg)
![2](https://user-images.githubusercontent.com/83620933/117602158-a0aa5080-b16d-11eb-99af-b00b47cc8505.jpg)
![3](https://user-images.githubusercontent.com/83620933/117602166-a56f0480-b16d-11eb-994e-40f80e4e4b58.jpg)
![4](https://user-images.githubusercontent.com/83620933/117602172-a99b2200-b16d-11eb-9131-bee07d5c4634.jpg)
![5](https://user-images.githubusercontent.com/83620933/117602179-ad2ea900-b16d-11eb-9b3b-720807cbf962.jpg)
![6](https://user-images.githubusercontent.com/83620933/117602193-b0299980-b16d-11eb-9312-ec093d686ec7.jpg)
![FINAL 2](https://user-images.githubusercontent.com/83620933/117835975-ef530a00-b295-11eb-8d4e-e31bd5a3ca41.jpg)

**Comment by A-b-h-i-s-h-e-k-D-u-t-t-a** [comment]
How to use Pepper spray.
Design version (rough) 1
![PG 1](https://user-images.githubusercontent.com/83583741/117603226-2c24e100-b170-11eb-82a3-d7fcd4618afc.jpg)
![PG2](https://user-images.githubusercontent.com/83583741/117603259-3e068400-b170-11eb-85cc-e071d6ced638.jpg)

Version 2
![2 FIN](https://user-images.githubusercontent.com/83583741/117603281-4fe82700-b170-11eb-9458-a2f7954b3819.jpg)

Final (Verticle al)

![portrait 22](https://user-images.githubusercontent.com/83583741/117759280-277c2d80-b241-11eb-9b5b-49a6974fdd36.jpg)

Horizontal al
![landscape 2](https://user-images.githubusercontent.com/83583741/117759492-817cf300-b241-11eb-9b3f-d9a8b197d637.jpg)

Mockup
![Mockup_3](https://user-images.githubusercontent.com/83583741/117759649-c012ad80-b241-11eb-9da0-b86922f82ea6.jpg)

**Comment by Suraj-Sadanandan** [comment]
how to start a scooter

1.
![P_20210509_194014_1](https://user-images.githubusercontent.com/83575714/117604399-e7e71000-b172-11eb-9a41-6216c4bb0561.jpg)

2.
![P_20210509_194820_1](https://user-images.githubusercontent.com/83575714/117604425-f7feef80-b172-11eb-9473-33a475627033.jpg)

3.
![P_20210510_101522_1](https://user-images.githubusercontent.com/83575714/117607419-8bd3ba00-b179-11eb-897e-f95c0af15255.jpg)

Final Outcome

![how-to](https://user-images.githubusercontent.com/83575714/117805387-8c05af80-b276-11eb-836a-1369e82b2e3f.jpg)

**Comment by Naman-Verma-gg** [comment]
**How to refill a soap dispenser :**
1
![Untitled-1](https://user-images.githubusercontent.com/83628869/117604913-2df0a380-b174-11eb-894b-33054ad9d84f.jpg)
2
![Untitled-2](https://user-images.githubusercontent.com/83628869/117604939-3ea11980-b174-11eb-91cf-cd5372083119.jpg)
3
![Untitled-3](https://user-images.githubusercontent.com/83628869/117604946-42cd3700-b174-11eb-9d0f-d78f5c80c4b3.jpg)
4
![Untitled-4](https://user-images.githubusercontent.com/83628869/117604955-4660be00-b174-11eb-83cc-308228a683db.jpg)
5
![Untitled-5](https://user-images.githubusercontent.com/83628869/117604967-4bbe0880-b174-11eb-9175-6f5b9fc9da75.jpg)


**FINAL SUBMISSION**
1) 3D horizontal :
![fin1](https://user-images.githubusercontent.com/83628869/117905995-b8124680-b2f1-11eb-928c-0da28eb0a48b.jpg)
 
2) 3D vertical :
![fin4](https://user-images.githubusercontent.com/83628869/117906063-d5dfab80-b2f1-11eb-97dc-cd2839644bcf.jpg)

3) 2D horizontal :
![fin3](https://user-images.githubusercontent.com/83628869/117906161-01fb2c80-b2f2-11eb-89c9-258dbe4890c1.jpg)

4) 2D vertical :
![fin2](https://user-images.githubusercontent.com/83628869/117906260-30790780-b2f2-11eb-86a4-37de02262371.jpg)

**Comment by NavdeepPKumar** [comment]
How to make a Face Shield -

Idea - 
![IMG_1596](https://user-images.githubusercontent.com/83628609/117605425-4614f280-b175-11eb-8a51-64b23b2ad0e2.jpeg)

Version 1 :
![IMG_1595](https://user-images.githubusercontent.com/83628609/117605454-5c22b300-b175-11eb-9366-324a4377dcd5.jpeg)

Version 2 :
![IMG_1594](https://user-images.githubusercontent.com/83628609/117605480-6f358300-b175-11eb-9207-4ae347f3d7d1.jpeg)

FINAL -
![0EEA193D-3AF7-4A17-A59D-4EF747F09B51](https://user-images.githubusercontent.com/83628609/117625808-09a4bf00-b194-11eb-8269-4227bfa6b54e.jpeg)

**Comment by mdawkhar** [comment]
### How to use Eye Dropper -

![20210510_094414](https://user-images.githubusercontent.com/83584046/117605587-b4f24b80-b175-11eb-8fdc-6629fe1a3998.jpg)
![20210510_094424](https://user-images.githubusercontent.com/83584046/117605590-b6237880-b175-11eb-8350-50fd7a0dc750.jpg)
![20210510_094439](https://user-images.githubusercontent.com/83584046/117605593-b7ed3c00-b175-11eb-9ab0-e6dbb00f2016.jpg)
![20210510_093450](https://user-images.githubusercontent.com/83584046/117605599-b9b6ff80-b175-11eb-9c04-aa7174039960.jpg)
![20210510_094238](https://user-images.githubusercontent.com/83584046/117605582-b0c62e00-b175-11eb-9aa5-66ea8259763e.jpg)
**Attempt 1**
![20210510_105059](https://user-images.githubusercontent.com/83584046/117609676-0c94b500-b17e-11eb-9910-0f8d0ec36404.jpg)
**Attempt 2**
![eye dropper](https://user-images.githubusercontent.com/83584046/117812263-3681d080-b27f-11eb-8f48-bbc83a842048.jpg)
Mockup
![mockup1](https://user-images.githubusercontent.com/83584046/117812862-f5d68700-b27f-11eb-966f-3c149a6fdb87.jpg)

### Final

![Eye_draft_2](https://user-images.githubusercontent.com/83584046/118350808-4f87cb80-b576-11eb-940d-c468c7294c9e.jpg)

Mockup
I searched for a mockup online which had a instructions paper coming out of the box but I couldn't find any. So, I made a mockup completely from scratch by making the box with paper.

![Mockup_2](https://user-images.githubusercontent.com/83584046/118350970-f79d9480-b576-11eb-8574-7b141c0c3379.jpg)

I used the below image to turn it into a mockup.

![raw](https://user-images.githubusercontent.com/83584046/118362000-511fb680-b5ab-11eb-8433-d7250b89ccd0.jpg)

**Comment by AjinkyaRaskar4** [comment]
How to start using a treadmill safely.
Version 1
![IMG_20210510_095921__01](https://user-images.githubusercontent.com/83605850/117606790-41057280-b178-11eb-9d56-8245e4ba9f32.jpg)
Version 2
![IMG_20210510_100007-01](https://user-images.githubusercontent.com/83605850/117606845-609c9b00-b178-11eb-94fc-9576595c0df6.jpeg)
Version 3
![IMG_20210511_112344__01__01](https://user-images.githubusercontent.com/83605850/117772661-08879680-b255-11eb-9705-f7003c5a1430.jpg)
Final
![01](https://user-images.githubusercontent.com/83605850/118157113-c9656b00-b437-11eb-8525-992dcc673a9c.jpg)

**Comment by tanushkasarang** [comment]
![Sev puri 1](https://user-images.githubusercontent.com/83626981/117607681-246a3a00-b17a-11eb-8262-39ea0b15d975.jpg)

**Layout 1                                                                                                               and                     Layout 3** in detail

![image](https://user-images.githubusercontent.com/83626981/118404675-87cffc80-b691-11eb-983a-77638e0a77c8.png)

Style used is soft pastels on black paper


![Style](https://user-images.githubusercontent.com/83626981/118408530-9c1cf500-b6a3-11eb-9c3d-ce3c50a01650.jpg)


Final: 
![image](https://user-images.githubusercontent.com/83626981/118408547-ad660180-b6a3-11eb-88e5-0386e4d20c8d.png)

**Comment by deep-savalia** [comment]
Version1: Top View

![IMG_20210510_095910_1](https://user-images.githubusercontent.com/83625972/117607783-57acc900-b17a-11eb-9cd0-1f2187cdedf9.png)

Version2: 

![IMG_20210510_101420_1](https://user-images.githubusercontent.com/83625972/117607789-5bd8e680-b17a-11eb-9f96-f9b57f0d6d34.png)

Version3: Side view

![Untitled design](https://user-images.githubusercontent.com/83625972/117607795-5ed3d700-b17a-11eb-853c-23f2e787a1d8.png)

Version4:

![IMG_20210510_095905_1](https://user-images.githubusercontent.com/83625972/117607799-5f6c6d80-b17a-11eb-8b41-5413c1107da4.png)

Final:

![IM](https://user-images.githubusercontent.com/83625972/118019458-a7f07a80-b376-11eb-8dca-fb82679078ff.png)

**Comment by PalakKatiyar09** [comment]
**DIFFERENT WAYS TO LACE SHOES**

ROUGH SKETCHES

![IMG_3925](https://user-images.githubusercontent.com/83607888/119562170-aa65c200-bdc3-11eb-8719-84fda8a947a2.JPG)

![IMG_3926](https://user-images.githubusercontent.com/83607888/119562061-8d30f380-bdc3-11eb-807a-886858f26731.JPG)

![IMG_3927](https://user-images.githubusercontent.com/83607888/119562079-915d1100-bdc3-11eb-937c-eb90cf87819d.JPG)

![IMG_3928](https://user-images.githubusercontent.com/83607888/119562088-93bf6b00-bdc3-11eb-837d-dec9b7846cfb.JPG)

![IMG_3929](https://user-images.githubusercontent.com/83607888/119562097-9621c500-bdc3-11eb-98cd-42d4260e567e.JPG)

**FINAL**
![final](https://user-images.githubusercontent.com/83607888/119562845-70e18680-bdc4-11eb-98ef-32d84884f991.png)

**Comment by KrishShah2** [comment]
Notes and steps
![IMG_20210511_104814](https://user-images.githubusercontent.com/83575362/117762318-87290780-b246-11eb-8009-572fe4c611d4.jpg)
Ideation 1
![IMG_20210511_104501](https://user-images.githubusercontent.com/83575362/117762327-898b6180-b246-11eb-973e-2a07baf7970e.jpg)
Ideation 2
![IMG_20210511_104655](https://user-images.githubusercontent.com/83575362/117762331-8b552500-b246-11eb-990a-e7b3be512bac.jpg)

Final Outcome
![Image188](https://user-images.githubusercontent.com/83575362/118377309-14bf7b00-b5ea-11eb-8461-3bf35a46c0e3.png)

**Comment by pavanxs** [comment]
How to refill Mechanical pencils
Version 1 simple process
![Untitled design](https://user-images.githubusercontent.com/83165442/118052898-32e66a80-b3a1-11eb-8426-ce708c437a44.png)
version 2 (with wrong assumptions)
![Untitled design](https://user-images.githubusercontent.com/83165442/118054027-2e22b600-b3a3-11eb-8e32-4469f94a7984.jpg)

**Comment by Shivankar03** [comment]
How to peel boiled egg easily
1.
![photo_2021-05-14_16-33-40](https://user-images.githubusercontent.com/83609772/118268711-60373380-b4db-11eb-99e9-48895e49a4e4.jpg)
2.
![photo_2021-05-14_16-33-56](https://user-images.githubusercontent.com/83609772/118268754-6a593200-b4db-11eb-88de-1ccb43779ff5.jpg)
3.
![photo_2021-05-14_16-34-01](https://user-images.githubusercontent.com/83609772/118268774-704f1300-b4db-11eb-99a9-58bd31f088f6.jpg)
final
![Wordless diagram](https://user-images.githubusercontent.com/83609772/118268873-97a5e000-b4db-11eb-86e3-3856a1334a1c.jpg)

**Comment by swapnildeycr** [comment]
![wordless_images](https://user-images.githubusercontent.com/83583900/118590521-370af180-b7c0-11eb-8b06-b26f6f5b0cf4.jpg)

Sir I have uploaded the work done so far. I will currently focus on doing the assignments at hand, but will try to improve on this whenever I have free time.

**Comment by 20U130022** [comment]
![jhgdf](https://user-images.githubusercontent.com/83587414/118987499-ef41c100-b99d-11eb-84a9-a94a38d278dc.jpg)
![jhgfxcfcfg](https://user-images.githubusercontent.com/83587414/118987503-f1a41b00-b99d-11eb-89f9-caf776ba1662.jpg)

**Comment by Numaan-Akhtar18** [comment]
Planning:
![IMG_20210628_000007](https://user-images.githubusercontent.com/83707499/123555648-a05d2780-d7a4-11eb-944a-bff6812b893f.jpg)
Rough idea:
![IMG_20210628_000127](https://user-images.githubusercontent.com/83707499/123555658-ac48e980-d7a4-11eb-9573-af4db905f38d.jpg)
![IMG_20210628_000157](https://user-images.githubusercontent.com/83707499/123555661-ae12ad00-d7a4-11eb-95f2-e52ebc022946.jpg)
Final:
![Untitled10_20210627131608](https://user-images.githubusercontent.com/83707499/123555747-44df6980-d7a5-11eb-9fa4-00a09788a0cb.png)

**Comment by abhishekshirsagar** [comment]
Sketch:
![image](https://user-images.githubusercontent.com/45625001/169664053-1d2bb3ab-d8fb-412f-8209-cad33c434bf1.png)

References: 
1. [https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/a05695fb-4289-46ae-aab1-7ba9fea88ec0/gr1.jpg](https://els-jbs-prod-cdn.jbs.elsevierhealth.com/cms/attachment/a05695fb-4289-46ae-aab1-7ba9fea88ec0/gr1.jpg)
2. [https://www.youtube.com/watch?v=w6IevIgUfxY](https://www.youtube.com/watch?v=w6IevIgUfxY)
